<h1 style="text-align:center;color:black;background-color:lightgreen;padding:10px;border-radius:8px;">Early Stage Diabetes Risk Prediction</h1>

### Introduction to Early Stage Diabetes Risk Prediction
Diabetes is one of the most common chronic diseases worldwide, affecting millions of people. It occurs when the body cannot produce enough insulin or cannot use insulin effectively, resulting in high blood glucose levels. Early detection of diabetes is important because it helps individuals take preventive measures, receive timely medical care, and reduce the risk of serious health complications.

The purpose of this analysis is to understand the key factors associated with early-stage diabetes risk and present meaningful insights through clear and effective data visualizations. This project uses Python libraries such as **Pandas, NumPy, Plotly, Matplotlib, and Seaborn** to analyze a diabetes dataset containing patient information, signs, and symptoms related to diabetes. The analysis aims to identify important patterns and relationships in the data, explore common diabetes-related symptoms, and understand the factors that may indicate an increased risk of developing diabetes. The insights obtained through data analysis and visualization can support early risk assessment and promote awareness of the importance of timely medical screening.

### Data Source
The dataset used in this project was identified through Google Dataset Search, which directed us to the original dataset hosted in the UCI Machine Learning Repository. The dataset is titled Early Stage Diabetes Risk Prediction Dataset and contains information about the signs and symptoms associated with early-stage diabetes.

Dataset Source:
https://archive.ics.uci.edu/dataset/529/early+stage+diabetes+risk+prediction+dataset

Note: The original dataset file was named diabetes_data_upload.csv. Only the file name was changed for project purposes; the original data structure and contents remain unchanged.


### Attribute Details

<table style="width:100%; border-collapse:collapse; font-size:14px;">
    <thead>
        <tr>
            <th style="width:22%; text-align:left; padding:6px; border-bottom:2px solid #ccc;">Attribute Name</th>
            <th style="width:78%; text-align:left; padding:6px; border-bottom:2px solid #ccc;">Description</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td style="padding:6px;">Age</td>
            <td style="padding:6px;">Represents the age of the patient in years. Age may be associated with the risk of developing diabetes.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Gender</td>
            <td style="padding:6px;">Represents the gender of the patient. The dataset includes Male and Female categories.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Polyuria</td>
            <td style="padding:6px;">Indicates whether the patient experiences excessive urination. Responses are recorded as Yes or No.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Polydipsia</td>
            <td style="padding:6px;">Indicates whether the patient experiences excessive thirst. Responses are recorded as Yes or No.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Sudden Weight Loss</td>
            <td style="padding:6px;">Indicates whether the patient has experienced sudden or unexplained weight loss.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Weakness</td>
            <td style="padding:6px;">Indicates whether the patient experiences general weakness or a lack of energy.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Polyphagia</td>
            <td style="padding:6px;">Indicates whether the patient experiences excessive hunger.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Genital Thrush</td>
            <td style="padding:6px;">Indicates whether the patient has experienced genital thrush, which may be associated with diabetes.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Visual Blurring</td>
            <td style="padding:6px;">Indicates whether the patient experiences blurred vision.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Itching</td>
            <td style="padding:6px;">Indicates whether the patient experiences itching of the skin.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Irritability</td>
            <td style="padding:6px;">Indicates whether the patient experiences unusual irritability or mood changes.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Delayed Healing</td>
            <td style="padding:6px;">Indicates whether wounds or injuries take longer than usual to heal.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Partial Paresis</td>
            <td style="padding:6px;">Indicates whether the patient experiences partial muscle weakness or reduced muscle movement.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Muscle Stiffness</td>
            <td style="padding:6px;">Indicates whether the patient experiences stiffness in the muscles.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Alopecia</td>
            <td style="padding:6px;">Indicates whether the patient experiences hair loss.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Obesity</td>
            <td style="padding:6px;">Indicates whether the patient is recorded as having obesity. Responses are recorded as Yes or No.</td>
        </tr>
        <tr>
            <td style="padding:6px;">Class</td>
            <td style="padding:6px;">Represents the target variable indicating the patient's recorded diabetes classification as Positive or Negative.</td>
        </tr>
    </tbody>
</table>

**Note:** Most symptom attributes are recorded as `Yes` or `No`. The `Gender` attribute contains Male and Female categories, `Age` is numerical, and `Class` is the target variable.

**Dataset Information:** The Early Stage Diabetes Risk Prediction dataset contains 520 patient records and 17 attributes, including the target variable. It provides demographic and symptom-related information for analyzing early-stage diabetes risk.

**Dataset Source:** [UCI Machine Learning Repository – Early Stage Diabetes Risk Prediction Dataset](https://archive.ics.uci.edu/dataset/529/early+stage+diabetes+risk+prediction+dataset)

**Important:** The dataset supports preliminary diabetes risk analysis and does not replace professional medical evaluation or laboratory testing.

### Imported Required Libraries
All neccessary Python libraries such as Pandas,Numpy,Plotly,Matplotlib,and Seaborn are imported for performing data loading,cleaning,exploration,and visualization.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

<h2 style="
    text-align:center;
    background-color:lightgreen;
    padding:10px 15px;
    border-radius:5px;
    color:black;
    font-size:30px
">
 Data Loading and Initial Overview
</h2>

This step focuses on importing the dataset and understanding its basic structure before starting the preprocessing phase.

#### Importing Required Libraries
Imported Python libraries such as Pandas,and Numpy for data manipulation and numerical operations.

In [2]:
import pandas as pd
import numpy as np

### Dataset Loading for Further Analysis

In [3]:
#Importing the Dataset
df=pd.read_csv("G:\\Data analystic\\Final_Project\\diabetes_data_upload.csv")

###  Initial Overview of the Dataset

In [4]:
#Displaying the Dimensions of the Dataset
print("Number of Rows:",df.shape[0])
print("Number of Columns:",df.shape[1])

Number of Rows: 520
Number of Columns: 17

### Displaying the First 5 Rows

In [5]:
df.head(5)

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

### Checking DataFrame Structural Summary

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 520 non-null    int64
 1   Gender              520 non-null    object
 2   Polyuria            520 non-null    object
 3   Polydipsia          520 non-null    object
 4   sudden weight loss  520 non-null    object
 5   weakness            520 non-null    object
 6   Polyphagia          520 non-null    object
 7   Genital thrush      520 non-null    object
 8   visual blurring     520 non-null    object
 9   Itching             520 non-null    object
 10  Irritability        520 non-null    object
 11  delayed healing     520 non-null    object
 12  partial paresis     520 non-null    object
 13  muscle stiffness    520 non-null    object
 14  Alopecia            520 non-null    object
 15  Obesity             520 non-null    object
 16  class               520 non-null    object
dtypes: int64(1), object(16)
memory usage: 69.2+ KB

### Checking Missing Values

In [7]:
df.isnull().sum()

Age                   0
Gender                0
Polyuria              0
Polydipsia            0
sudden weight loss    0
weakness              0
Polyphagia            0
Genital thrush        0
visual blurring       0
Itching               0
Irritability          0
delayed healing       0
partial paresis       0
muscle stiffness      0
Alopecia              0
Obesity               0
class                 0
dtype: int64

### Displaying Statistical Summary

In [8]:
df.describe()

              Age
count  520.000000
mean    48.028846
std     12.151466
min     16.000000
25%     39.000000
50%     47.500000
75%     57.000000
max     90.000000

<h2 style="
    text-align:center;
    background-color:lightgreen;
    padding:10px 15px;
    border-radius:5px;
    color:black;
    font-size:30px
">
 Data Preprocessing
</h2>

This step ensures the dataset is clean,consistent,and suitable for analysis.The cleaning steps include (1)**Handling missing values**,(2)**Removing duplicates**,(3)**Creating Derived columns**,(4)**Standardizing column names and Categorical values**(5)**Correcting Data Types**(6)**Removing unnecessary columns**,(7)**Filtering data**.

### (1)Handling Missing Values
The dataset was examined for missing values (NaN) across all columns. The analysis confirmed that there are no missing values in the dataset. Therefore, no missing-value imputation or replacement techniques were required. All records were retained for further data preprocessing, exploratory data analysis, and visualization. This ensures that the dataset is complete with respect to missing values and ready for subsequent analysis

### (2)Removing Duplicates

In [9]:
print("Duplicate Rows Found:",df.duplicated().sum())

Duplicate Rows Found: 269

In [10]:
print("Number of Duplicate Rows:",df.drop_duplicates(inplace=True))

Number of Duplicate Rows: None

In [11]:
print("Dataset Dimensions:",df.shape)

Dataset Dimensions: (251, 17)

In [12]:
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive

### (3)Creating Derived Columns
In this step,new columns such as **Age Group and **Symptom Count are created to organize the data into clearer categories for analysis.

In [13]:
#Displaying Columns Before Derived
print("Current column names:",df.columns.tolist())

Current column names: ['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia', 'Obesity', 'class']

### Firts column:Age Group
This will help you analyze how diabetes classification varies across different age groups.

In [14]:

# Create Age Groups
age = [0, 29, 44, 59, float('inf')]
group = ['Young', 'Adult', 'Middle-aged', 'Senior']

df['Age Group'] = pd.cut(df['Age'],bins=age,labels=group,include_lowest=True)

# Display the results
print(df[['Age', 'Age Group']].head(10))

# Count patients in each age group
print(df['Age Group'].value_counts().sort_index())

   Age    Age Group
0   40        Adult
1   58  Middle-aged
2   41        Adult
3   45  Middle-aged
4   60       Senior
5   55  Middle-aged
6   57  Middle-aged
7   66       Senior
8   67       Senior
9   70       Senior
Age Group
Young           9
Adult          89
Middle-aged    97
Senior         56
Name: count, dtype: int64

### Second Column : Symptom Count

In [15]:
#create column for symptom count
# List of symptom columns
symptom_columns = [
    'Polyuria',
    'Polydipsia',
    'sudden weight loss',
    'weakness',
    'Polyphagia',
    'Genital thrush',
    'visual blurring',
    'Itching',
    'Irritability',
    'delayed healing',
    'partial paresis',
    'muscle stiffness',
    'Alopecia',
    'Obesity'
]

# Count the Yes responses in each row
df['Symptom Count'] = (df[symptom_columns].apply(lambda col: col.astype(str).str.strip().str.lower().eq('yes')).sum(axis=1))

print(df[['Age', 'Symptom Count', 'class']].head(10))

   Age  Symptom Count     class
0   40              7  Positive
1   58              4  Positive
2   41              7  Positive
3   45              6  Positive
4   60             13  Positive
5   55             10  Positive
6   57              7  Positive
7   66              9  Positive
8   67             10  Positive
9   70              8  Positive

In [16]:
#Displaying Columns Before Derived
print("Current column names:",df.columns.tolist())

Current column names: ['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia', 'Obesity', 'class', 'Age Group', 'Symptom Count']

In [17]:
#Displaying Updated Column Names
print("Updated Column Names:",df.columns)

Updated Column Names: Index(['Age', 'Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss',
       'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring',
       'Itching', 'Irritability', 'delayed healing', 'partial paresis',
       'muscle stiffness', 'Alopecia', 'Obesity', 'class', 'Age Group',
       'Symptom Count'],
      dtype='object')

### Standardizing Column Names and Categorical Values

Column Names: The column names in the Early Stage Diabetes Risk Prediction dataset were checked to ensure consistency and readability. Unnecessary spaces were removed, and column names were reviewed to maintain a consistent naming convention. The original column names were retained where appropriate to avoid affecting the existing data processing steps.

### 4.Correcting Data Types
In this step, the data types of all columns in the Early Stage Diabetes Risk Prediction dataset were checked to ensure they were appropriate for data analysis.Therefore, no additional data type corrections were required.

In [18]:

# Check data types of all columns
print("Data Types of All Columns:")
print(df.dtypes)

# Check whether any column has a missing data type
print("\nData type verification:")
print(df.dtypes.info() if False else "All column data types are assigned.")

# Display numerical and categorical columns separately
print("\nNumerical Columns:")
print(df.select_dtypes(include=['int64', 'float64']).columns.tolist())

print("\nCategorical Columns:")
print(df.select_dtypes(include=['object', 'category']).columns.tolist())

Data Types of All Columns:
Age                      int64
Gender                  object
Polyuria                object
Polydipsia              object
sudden weight loss      object
weakness                object
Polyphagia              object
Genital thrush          object
visual blurring         object
Itching                 object
Irritability            object
delayed healing         object
partial paresis         object
muscle stiffness        object
Alopecia                object
Obesity                 object
class                   object
Age Group             category
Symptom Count            int64
dtype: object

Data type verification:
All column data types are assigned.

Numerical Columns:
['Age', 'Symptom Count']

Categorical Columns:
['Gender', 'Polyuria', 'Polydipsia', 'sudden weight loss', 'weakness', 'Polyphagia', 'Genital thrush', 'visual blurring', 'Itching', 'Irritability', 'delayed healing', 'partial paresis', 'muscle stiffness', 'Alopecia', 'Obesity', 'class', 'Age Group']

### 5.Filtering Data
This step ensures the dataset only contains meaningful and valid observations.

In [19]:
df.head()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,Adult,7
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,Middle-aged,4
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,Adult,7
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,Middle-aged,6
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,Senior,13

Display only male records:

In [20]:
male_data = df[df['Gender'] == 'Male']

print("Male records:")
display(male_data)
print("Number of male records:", len(male_data))

Male records:

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,Adult,7
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,Middle-aged,4
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,Adult,7
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,Middle-aged,6
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,Senior,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,54,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Middle-aged,0
510,67,Male,No,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,No,Negative,Senior,4
511,66,Male,No,No,No,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,No,Negative,Senior,8
512,43,Male,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,Negative,Adult,1
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0

Number of male records: 160

Display only female records:

In [21]:
female_data = df[df['Gender'] == 'Female']

print("Female records:")
display(female_data)
print("Number of female records:", len(female_data))

Female records:

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
39,30,Female,Yes,No,Yes,Yes,Yes,No,No,No,No,Yes,No,No,No,No,Positive,Adult,5
40,53,Female,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,Positive,Middle-aged,9
41,50,Female,Yes,Yes,Yes,No,Yes,No,No,No,No,Yes,Yes,No,No,No,Positive,Middle-aged,6
42,50,Female,No,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Positive,Middle-aged,9
43,35,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,No,Yes,Yes,Yes,No,No,Positive,Adult,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,54,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive,Middle-aged,6
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive,Adult,7
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive,Middle-aged,9
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive,Middle-aged,9
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative,Adult,5

Number of female records: 91

Display patients aged 40 or above:

In [22]:
age_filtered_data = df[df['Age'] >= 40]

display(age_filtered_data)
print("Records with age 40 or above:", len(age_filtered_data))

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,Adult,7
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,Middle-aged,4
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,Adult,7
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,Middle-aged,6
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,Senior,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,62,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,Yes,Positive,Senior,7
514,54,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive,Middle-aged,6
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive,Middle-aged,9
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive,Middle-aged,9
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0

Records with age 40 or above: 183

Display records labelled Positive:

In [23]:
positive_data = df[df['class'] == 'Positive']

display(positive_data)
print("Positive records:", len(positive_data))

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive,Adult,7
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive,Middle-aged,4
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive,Adult,7
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive,Middle-aged,6
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive,Senior,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
513,62,Female,Yes,Yes,Yes,Yes,No,No,Yes,No,No,No,Yes,No,No,Yes,Positive,Senior,7
514,54,Female,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,No,No,Positive,Middle-aged,6
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive,Adult,7
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive,Middle-aged,9
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive,Middle-aged,9

Positive records: 173

Display records labelled Negative:

In [24]:
negative_data = df[df['class'] == 'Negative']

display(negative_data)
print("Negative records:", len(negative_data))

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class,Age Group,Symptom Count
200,40,Male,No,Yes,Yes,Yes,No,No,Yes,Yes,No,No,Yes,Yes,No,No,Negative,Adult,7
201,28,Male,No,No,Yes,No,No,No,No,No,No,No,No,No,No,No,Negative,Young,1
202,37,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0
203,34,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0
204,30,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
510,67,Male,No,No,No,Yes,No,No,No,Yes,No,Yes,No,No,Yes,No,Negative,Senior,4
511,66,Male,No,No,No,Yes,Yes,No,Yes,Yes,No,Yes,Yes,Yes,Yes,No,Negative,Senior,8
512,43,Male,No,No,No,No,No,No,No,No,No,No,No,No,Yes,No,Negative,Adult,1
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative,Adult,5
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative,Adult,0

Negative records: 78

<div style=" margin-top:15px;background:lightgreen;padding:12px 16px;border-left:5px solid #2ecc71;border-radius:6px;font-family:Arial,sans-serif;font-weight:bold;color:black;">✔ Data Preprocessing was successfully completed !!  Ensuring the dataset is clean,consistent,and ready for analysis.</div>